// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD54pY_OGtS81lzspBaUNEt_rKrmaWhoYk',
    appId: '1:222445823239:web:60092d7678129c12c611a2',
    messagingSenderId: '222445823239',
    projectId: 'billsplug-6a6a1',
    authDomain: 'billsplug-6a6a1.firebaseapp.com',
    storageBucket: 'billsplug-6a6a1.firebasestorage.app',
    measurementId: 'G-SBFTLP4NLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4XxGjpE3kTaRG9TD1ommP_NkV9izvZM',
    appId: '1:222445823239:android:c1ae89364a20c787c611a2',
    messagingSenderId: '222445823239',
    projectId: 'billsplug-6a6a1',
    storageBucket: 'billsplug-6a6a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtTuN0P-aCTFtzkocD9hmw4lO0Ks9mo-Q',
    appId: '1:222445823239:ios:cf88026200446d42c611a2',
    messagingSenderId: '222445823239',
    projectId: 'billsplug-6a6a1',
    storageBucket: 'billsplug-6a6a1.firebasestorage.app',
    iosBundleId: 'com.billsplug.billsPlug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtTuN0P-aCTFtzkocD9hmw4lO0Ks9mo-Q',
    appId: '1:222445823239:ios:cf88026200446d42c611a2',
    messagingSenderId: '222445823239',
    projectId: 'billsplug-6a6a1',
    storageBucket: 'billsplug-6a6a1.firebasestorage.app',
    iosBundleId: 'com.billsplug.billsPlug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD54pY_OGtS81lzspBaUNEt_rKrmaWhoYk',
    appId: '1:222445823239:web:03021fb8407e5b38c611a2',
    messagingSenderId: '222445823239',
    projectId: 'billsplug-6a6a1',
    authDomain: 'billsplug-6a6a1.firebaseapp.com',
    storageBucket: 'billsplug-6a6a1.firebasestorage.app',
    measurementId: 'G-9P470FVZ3S',
  );
}
